version: '3'

services:
  server:
    network_mode: host
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./images:/srv
      - ./index.html:/etc/nginx/html/index.html
      - ./pdf_fs/epub_fs:/epub
      - ./nginx.conf:/etc/nginx/conf.d/default.conf